# Generated by Django 5.0.1 on 2024-02-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
