# Generated by Django 5.0.1 on 2024-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
